apiVersion: v1
kind: Service
metadata:
  name: securekubeops-service
  namespace: dev
  labels:
    app: securekubeops
spec:
  selector:
    app: securekubeops
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort